app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin
from app import db, login_manager

registrations = db.Table('registrations',
	db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
	db.Column('session_id', db.Integer, db.ForeignKey('sessions.id')))

class User(UserMixin, db.Model):
	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(64), unique=True, index=True)
	email = db.Column(db.String(64), unique=True, index=True)
	password_hash = db.Column(db.String(128))
	sessions = db.relationship('ProgramSession',
								secondary=registrations,
								backref=db.backref('users', lazy='dynamic'),
								lazy='dynamic')

	@property 
	def password(self):
		'''
			This function raises an error if you try to read the password value.
		'''
		raise AttributeError('password cannot be read (write-only attribute)')

	@password.setter
	def password(self, password):
		'''
			Generates an password hash for a given password.
		'''
		self.password_hash = generate_password_hash(password)


	def verify_password(self, password):
		'''
			Compares the hash stored in the database with the
			password value given by user.
		'''
		return check_password_hash(self.password_hash, password)

	@login_manager.user_loader
	def load_user(user_id):
		'''	
			Is a Flask-Login callback function.
			It loads a user, given the identifier.
		'''
		return User.query.get(int(user_id))

class ProgramSession(db.Model):
	__tablename__ = 'sessions'

	id = db.Column(db.Integer, primary_key=True)
	session_name = db.Column(db.String(128), unique=True, index=True)
	session_url = db.Column(db.String(128))
	program_lang = db.Column(db.String(128))


	

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User, ProgramSession

class NewSessionForm(Form):
	session_name = StringField('Session Name:', validators=[Required(), Length(1, 64)])
	program_lang = SelectField('Language you prefer:', choices=[('js', 'javascript'),
                                                             ('erb', 'ruby'), ('java', 'java'), ('cpp', 'C++'),
                                                             ('py', 'Python'), ('text', 'Plain Text')])
	submit = SubmitField('Create Session')

app/__init__.py
from flask import Flask, render_template
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.mail import Mail
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
#Initialization of the Flask-Login
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
	'''
		Is a factory function which allows specification of 
		cofigurations before the app is created.
		It takes as an argument the name of a configuration 
		to use for the application.
		
	'''
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)
	login_manager.init_app(app)
	mail.init_app(app)
	bootstrap.init_app(app)
	db.init_app(app)

	from main import main as main_blueprint
	from auth import auth as auth_blueprint

	app.register_blueprint(main_blueprint)
	app.register_blueprint(auth_blueprint)
	return app

app/main/__init__.py
from flask import Blueprint 

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, request, Response, jsonify
from flask.ext.login import current_user, login_required
from . import main
from .. import db
from..models import User, ProgramSession
from . forms import NewSessionForm
from firebase import firebase
from app.email import send_email

session_url = ""

@main.route('/', methods=['GET', 'POST'])
def start():
	
	return render_template('start.html')

@main.route('/index', methods=['GET', 'POST'])
def index():
    
    return render_template('index.html')

@main.route('/new_session', methods=['GET', 'POST'])
def new_session():
	''' This function facilitates the creation of new pair programming sessions '''
	form = NewSessionForm()
	if form.validate_on_submit():
		sess = ProgramSession(session_name=form.session_name.data, program_lang=form.program_lang.data)
		if current_user.id is not None:
			user = User.query.get(current_user.id)
			user.sessions.append(sess)
			db.session.add(user)
			db.session.commit()
		return redirect(url_for('main.invite'))
	return render_template('main/new_session.html', form=form)

@main.route('/invite', methods=['GET', 'POST'])
@login_required
def invite():
    users = User.query.all()
    if request.method == 'POST':
        for user in users:
            print user.username == str(request.form.get('usernames'))
            if str(user.username) == str(request.form.get('usernames')):
                session_link = request.form.get('session_link')
                send_email(current_user.email, user.email, "Join me in my session!", 'mail/invite', user=user,  current_user=current_user, session_link=session_link)
                print str(session_link)
                print True

    return render_template('main/home.html', users=users)
 
@main.route('/sessions', methods=['GET', 'POST'])
@login_required
def my_session():
        firebase_ = firebase.FirebaseApplication('https://pairprogram.firebaseio.com/')
        results = firebase_.get('https://pairprogram.firebaseio.com/', None)
        sess_hash = []
        for item in results:
            for first_name in results[item]:
                if str(current_user.username) == str(results[item][first_name].get('username')).strip():
                    # print results[item][first_name].get('username')
                    sess_hash.append(str(results[item][first_name].get('session')))
        return render_template('main/my_session.html', sess_hash=sess_hash)

@main.route('/edit/<hashed>')
def edit(hashed):
    global session_url
    session_url = "http://pprogram.herokuapp.com/invite#"+hashed
    return redirect(session_url)

@main.route('/delete/<hashed>')
def delete(hashed):
    firebase_ = firebase.FirebaseApplication('https://pairprogram.firebaseio.com/')
    results = firebase_.get('https://pairprogram.firebaseio.com/', None)
    for item in results:
        for n in results[item]:
            if str(current_user.username) == str(results[item][n].get('username')).strip():
                print results[item][n].get('session')
                print "Hashed -->"+hashed
                if results[item][n].get('session') == hashed:
                    print True
                    print current_user.username
                    firebase_.delete(current_user.username + '  ', item)
    return redirect(url_for('main.my_session'))

@main.route('/chat')
@login_required
def chat():
    return render_template('main/chat.html')

@main.route('/chat_session')
@login_required
def chat_session():
    return render_template('main/chat_session.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}Pair Program{% endblock %}
{% block head %} 
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://cdn.firebase.com/libs/firepad/1.3.0/firepad.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename="css/style.css") }}" />

    <!-- Firebase -->
    <script src="https://cdn.firebase.com/js/client/2.3.2/firebase.js"></script>

    <!-- ACE and its JavaScript mode and theme files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/ace.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/mode-javascript.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/theme-textmate.js"></script>

    <!-- Firepad -->
    <link rel="stylesheet" href="https://cdn.firebase.com/libs/firepad/1.3.0/firepad.css" />
    <script src="https://cdn.firebase.com/libs/firepad/1.3.0/firepad.min.js"></script>

    <!-- Firechat -->
    <link rel='stylesheet' href='https://cdn.firebase.com/libs/firechat/2.0.1/firechat.min.css' />
    <script src='https://cdn.firebase.com/libs/firechat/2.0.1/firechat.min.js'></script>
    
    <style>
    html { height: 100%; }
    body { margin: 0; height: 100%; position: relative; }
    /* Height / width / positioning can be customized for your use case.
       For demo purposes, we make firepad fill the entire browser. */
    #firepad{
        margin: 0 auto;
        /*height: 80%;
        width: 60%;*/
        background: #FFF5C3;
    }

    #firechat-wrapper{
        height: 475px;
        max-width: 325px;
        padding: 10px;
        border: 1px solid #ccc;
        background-color: #fff;
        margin: 50px auto;
        text-align: center;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0 5px 25px #666;
        -moz-box-shadow: 0 5px 25px #666;
        box-shadow: 0 5px 25px #666;
      } 
      
    </style>
   
{% endblock %}
{% block body %}
    {% block navbar %}
        <header>
        <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index">PairProgram</a>
            </div>
           <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('main.index') }}">Home</a></li>
                        <li><a href="{{ url_for('main.index') }}">Chat</a></li>
                    {% endif %}
                
                   
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                    {% endif %}
            </ul>
            </div>
        </div>
        </div>
        </header>
    {% endblock navbar %}
    {% block content %}
        <div class="container">
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %} 
                {% block page_content %}{% endblock %}
        </div>
    {% endblock content %}
                   
    {% block scripts %}
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/editor.js') }}"></script>
        <script>
                function initChat(authData) {
                var chat = new FirechatUI(chatRef, document.getElementById('firechat-wrapper'));
                chat.setUser(authData.uid, authData[authData.provider].displayName);
                  }
        </script>        
        
            
    {% endblock %}
                
    {% endblock body %}

   

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<div class="container">

    <p>
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        {% if dismissable %}
             <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% endif %}
             {{ message }}
        </div>
    {% endfor %}

    <div class="center jumbotron">     
        <h2> Pair Program</h2><br>
        <p>Lets do this</p>
        <p><a class="btn btn-primary btn-lg login-btn" href="/login" role="button">Login to Continue!</a></p>
    </div>
{% endblock %}

app/templates/main/chat.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Pair App{% endblock%}
{% block page_content %}

	<div class="page-header">
		<h1> Chat </h1>
	</div>
		<script>
		// Create a new Firebase reference, and a new instance of the Login client
		var chatRef = new Firebase('https://pairprogram.firebaseio.com/chat');

		function login() {
		  chatRef.authWithOAuthPopup("twitter", function(error, authData) {
		    if (error) {
		      console.log(error);
		    }
		  });
		}

		chatRef.onAuth(function(authData) {
		  // Once authenticated, instantiate Firechat with our user id and user name
		  if (authData) {
		    initChat(authData);
		  }
		});
		</script>

		<a href="{{ url_for('main.chat_session') }}" onclick='login();'>Login with Twitter</a>
	</div>
	
{% endblock %}

app/templates/main/chat_session.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Pair App{% endblock%}
{% block page_content %}

	

	<div id='firechat-wrapper'></div>
	
{% endblock %}

app/templates/main/home.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html"  as wtf %}

{% block title %}Pair App{% endblock%}
{% block content %}

<p id="username" hidden>{{ current_user.username }}</p>
<p id="session_id" hidden>{{ current_user.id }}</p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>Invite</h2>
        <form method="post" action="{{ url_for('main.invite')}}" >
          <div class="form-group">
            <label for="first_cell">Select a user</label>
              <select class="form-control" name="usernames">
              {% for user in users%}
                <option value="{{ user.username }}">{{ user.username}}</option>
              {% endfor %}
              </select>
              
                <div class="form-group">
                        <label for="session_link">Session Link:</label>
                        <input  class="form-control"  name="session_link" placeholder="Paste your session link">
                </div>
              </div>
              <input type="submit" class="btn btn-primary" value="Send Invite">
        </form>
        </div>
        <div class="col-md-8"> 
        <div id="firepad"></div>
        </div>
        <div class="col-md-2">
           
        </div>
        {% block scripts %} {{super()}}
          <!-- firebase -->
          <script src="https://cdn.firebase.com/js/client/2.3.2/firebase.js"></script>
          <!-- ace  -->
          <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/ace.js"></script>
          <!-- firepad -->

          <script src="https://cdn.firebase.com/libs/firepad/1.3.0/firepad.js"></script>
          <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
          <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

              
{% endblock %} 
{% endblock %} 

app/templates/main/my_session.html
{% extends "base.html" %}
{% block content %}


<div class="container">
  <h2>My Sessions</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Sessions</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
        {% for item in sess_hash %}
            <tr>
                <td>{{ item }}</td>
                <td><a href="{{ url_for('main.edit', hashed=item) }}">Edit</a></td>
                <td><a href="{{ url_for('main.delete', hashed=item) }}">Delete</a></td>
                
            </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/main/new_session.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Pair App{% endblock%}
{% block page_content %}

	<div class="page-header">
		<h1> Create Session </h1>
	</div>
	<div class="col-md-4">
		{{ wtf.quick_form(form) }}
	</div>
	
{% endblock %}

app/templates/start.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<div class="container">

    <p>
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        {% if dismissable %}
             <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% endif %}
             {{ message }}
        </div>
    {% endfor %}

    <div class="center jumbotron">     
        <h2>PAIR PROGRAM</h2><br>
        <p> Hey there coders! Get ready to rumble!!</p>
        <p><a class="btn btn-primary btn-lg login-btn" href="/login" role="button">Login to continue</a></p>
    </div>

    
{% endblock %}